### ISSUE TITLE
Add two buttons and an imageview

### ISSUE THREAD

**Issue by ak523** [clubgamma/Random-Meme-Generator-App#1]
Add two buttons one for watching next meme and one button for sharing current meme, also add an imageview for displaying the current randomly generated meme.

It should look like this:
![115365489-0eec9a80-a1e2-11eb-8f62-534bbcee759c](https://user-images.githubusercontent.com/52751750/135430478-9167e580-9f7d-4cb2-8e53-51c5e2b3318d.png)

**Comment by Flamingloon** [comment]
@ak523 please assign me this issue

**Comment by ak523** [comment]
> @ak523 please assign me this issue

@Flamingloon Sure, but read the readme and contributing guidelines first.

**Comment by KeneePatel** [comment]
This issue has been resolved and merged in this PR #4 . So it would be just better to close it guess to avoid misunderstandings.

**Comment by ak523** [comment]
> This issue has been resolved and merged in this PR #4 . So it would be just better to close it guess to avoid misunderstandings.

@Flamingloon Thanks for contributing to club Gamma open-source project 😊 and @KeneePatel Thanks for reminding😃 .
