### ISSUE TITLE
Add a starting main page

### ISSUE THREAD

**Issue by Kajal13081** [clubgamma/Random-Meme-Generator-App#10]
I would like to add a starting page where user can click on button and go to next page to enjoy the meme. And also a toast will appear saying "Opening meme page. Enjoy!!"
@ak523 Please do review this issue

**Comment by ak523** [comment]
@Kajal13081 That is a great idea!👌 just one thing make sure you add description in that first page in which user gets an idea of what this app does.
Happy coding!

**Comment by detherminal** [comment]
@ak523 when will you merge my pull request? 

https://github.com/clubgamma/Random-Meme-Generator-App/pull/8

**Comment by Kajal13081** [comment]
> @Kajal13081 That is a great idea!👌 just one thing make sure you add description in that first page in which user gets an idea of what this app does. And make sure to read the readme and contributing.md before contributing😄. Happy coding!

Sure. ✌

**Comment by Kajal13081** [comment]
#14 pr added @ak523

**Comment by ak523** [comment]
#14 fixes this.
