### ISSUE TITLE
UI Improvement and Loading icon when next is clicked

### ISSUE THREAD

**Issue by alok27a** [clubgamma/Random-Meme-Generator-App#13]
Pls assign the issue to me as Hacktoberfest2021

**Comment by alok27a** [comment]
Can I work on it?

**Comment by ramisha-anwer** [comment]
@ak523 Hey, have fixed this issue. Kindly check my PR #15

**Comment by alok27a** [comment]
@ak523 Can I work on improvement of the UI then?

**Comment by ak523** [comment]
@alok27a  Yeah sure you can work on UI improvement😄. Read the readme and contributing.md before contributing.
Happy coding!

**Comment by Positron007** [comment]
hey i would like to work on it
