### ISSUE TITLE
Add sharing funtionality

### ISSUE THREAD

**Issue by ak523** [clubgamma/Random-Meme-Generator-App#2]
Add sharing functionality in which user can share the currently displayed meme image to others.

**Comment by KeneePatel** [comment]
I would like to get assigned in this issue.

**Comment by ak523** [comment]
@KeneePatel Make sure to read the readme and contributing guidelines before making a contribution😄.

**Comment by unnikrishnan2002** [comment]
@ak523 I would like to work on this issue

**Comment by KeneePatel** [comment]
@unnikrishnan2002 Honestly u can try, but I have already implemented and tested it making a PR right now. So..... yea

**Comment by unnikrishnan2002** [comment]
> @unnikrishnan2002 Honestly u can try, but I have already implemented and tested it making a PR right now. So..... yea

ohh okay no problem
