### ISSUE TITLE
Getting data from the API

### ISSUE THREAD

**Issue by ak523** [clubgamma/Random-Meme-Generator-App#3]
Getting meme image data from the API mentioned in README.md and displaying meme images in the imageview, and make sure to add functionality to move to next meme image.

**Comment by CH1NRU5T** [comment]
I would like to work on this.
Could you assign me this ?

**Comment by ak523** [comment]
> I would like to work on this. Could you assign me this ?
@CH1NRU5T  Yeah you can work on this issue and read the readme and contributing.md before contributing.

**Comment by ak523** [comment]
#6  fixes #3
