### ISSUE TITLE
Add app launcher icon

### ISSUE THREAD

**Issue by ak523** [clubgamma/Random-Meme-Generator-App#7]
Create and add attractive-looking app launcher icon.

**Comment by Positron007** [comment]
Hey I want to work on it.

**Comment by ak523** [comment]
@Positron007 Read the readme and contributing.md before contributing😄.

**Comment by detherminal** [comment]
Hello. I want to make it.

**Comment by detherminal** [comment]
Hello. I added a app icon and opened a pull request. 

https://github.com/clubgamma/Random-Meme-Generator-App/pull/8

**Comment by Positron007** [comment]
Hi there👋,
Added the app launcher icon, completed the assigned task.
Hope you merge the PR.

**Comment by namra4122** [comment]
Hello. I want to make it.

**Comment by ak523** [comment]
#9 fixes this issue.
